# Generated by Django 3.2.6 on 2022-07-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.CharField(max_length=25)),
                ('script', models.FileField(upload_to='')),
                ('Lenguaje', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=75)),
                ('os', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title_1', models.CharField(blank=True, max_length=50)),
                ('content_1', models.TextField(blank=True)),
                ('nombreco_1', models.CharField(blank=True, max_length=50)),
                ('code_1', models.TextField(blank=True)),
                ('cita_1', models.CharField(blank=True, max_length=50)),
                ('title_2', models.CharField(blank=True, max_length=50)),
                ('content_2', models.TextField(blank=True)),
                ('nombreco_2', models.CharField(blank=True, max_length=50)),
                ('code_2', models.TextField(blank=True)),
                ('cita_2', models.CharField(blank=True, max_length=50)),
                ('title_3', models.CharField(blank=True, max_length=50)),
                ('content_3', models.TextField(blank=True)),
                ('nombreco_3', models.CharField(blank=True, max_length=50)),
                ('code_3', models.TextField(blank=True)),
                ('cita_3', models.CharField(blank=True, max_length=50)),
                ('title_4', models.CharField(blank=True, max_length=50)),
                ('content_4', models.TextField(blank=True)),
                ('nombreco_4', models.CharField(blank=True, max_length=50)),
                ('code_4', models.TextField(blank=True)),
                ('cita_4', models.CharField(blank=True, max_length=50)),
                ('title_5', models.CharField(blank=True, max_length=50)),
                ('content_5', models.TextField(blank=True)),
                ('nombreco_5', models.CharField(blank=True, max_length=50)),
                ('code_5', models.TextField(blank=True)),
                ('cita_5', models.CharField(blank=True, max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
