# Generated by Django 3.2.6 on 2022-12-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cita_1',
            field=models.CharField(blank=True, max_length=725),
        ),
        migrations.AlterField(
            model_name='post',
            name='cita_2',
            field=models.CharField(blank=True, max_length=725),
        ),
        migrations.AlterField(
            model_name='post',
            name='cita_3',
            field=models.CharField(blank=True, max_length=725),
        ),
        migrations.AlterField(
            model_name='post',
            name='cita_4',
            field=models.CharField(blank=True, max_length=725),
        ),
        migrations.AlterField(
            model_name='post',
            name='cita_5',
            field=models.CharField(blank=True, max_length=725),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombreco_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombreco_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombreco_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombreco_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombreco_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_2_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_2_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_2_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_2_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_1_2_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_2_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_2_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_2_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_2_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_2_2_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_2_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_2_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_2_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_2_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_3_2_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_2_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_2_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_2_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_2_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_4_2_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_2_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_2_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_2_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_2_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='puntotitle_5_2_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_1_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_1_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_1_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_1_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_1_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_2_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_2_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_2_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_2_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_2_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_3_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_3_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_3_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_3_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_3_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_4_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_4_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_4_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_4_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_4_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_5_1_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_5_1_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_5_1_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_5_1_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_5_1_5',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_1',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_2',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_3',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_4',
            field=models.CharField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_5',
            field=models.CharField(blank=True, max_length=175),
        ),
    ]
